name: Deploy to Vercel

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 2'
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: Install datasette and vercel plugin
      run: pip install datasette datasette-publish-vercel
    - name: Deploy Datasette using Vercel
      env:
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      run: |-
        datasette publish vercel prisma/transcripts.db \
          --token $VERCEL_TOKEN \
          --project motley-fool-earning-transcripts \
          --metadata datasette-metadata.json
