name: Deploy to Fly

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Install datasette and plugins
      run: pip install datasette datasette-publish-fly
    - name: Deploy Datasette using Fly
      run: |-
        datasette publish fly prisma/transcripts.db \
          --app motley-fool-earning-transcripts \
          --metadata datasette-metadata.json
