name: Scrape earning call transcripts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install Node dependencies
      run: npm install
    - name: Run scripts
      run: npm start
    - name: Commit and push if it changed
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add prisma
        git pull origin $GITHUB_REF
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push